### ISSUE TITLE
Import-DatabricksFolder randomly fails with missing CmdLet Start-ThreadJob

### ISSUE THREAD

**Issue by elwinarens** [DataThirstLtd/azure.databricks.cicd.tools#156]
`Import-DatabricksFolder` randomly fails with missing CmdLet `Start-ThreadJob` for Azure Pipeline task `DataThirstLtd.databricksDeployScriptsTasks.databricksDeployScriptsTask.databricksDeployScripts@0` being run on a window agent.

Error log:
```
Running without clean
##[debug]Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_ComputerSystem'.
##[debug]Operation 'Enumerate CimInstances' complete.
##[debug]POST https://westeurope.azuredatabricks.net/api/2.0/workspace/mkdirs with -1-byte payload
##[debug]received 3-byte response of content type application/json

##[debug]Path: /example/path
##[debug]Pushing file convoy_runner.py to /example/path/example_notebook
##[debug]Leaving C:\Data\Agent\_work\_tasks\databricksDeployScripts_e7e6f2ae-fe5e-4191-9fd3-dbd811fa72e7\0.9.2916\vstsDeploy.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Import-DatabricksFolder : The term 'Start-ThreadJob' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]At C:\Data\Agent\_work\_tasks\databricksDeployScripts_e7e6f2ae-fe5e-4191-9fd3-dbd811fa72e7\0.9.2916\vstsDeploy.ps1:53 char:9
##[debug]+         Import-DatabricksFolder -LocalPath $localPath -DatabricksPath ...
##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : ObjectNotFound: (Start-ThreadJob:String) [Import-DatabricksFolder], CommandNotFoundExcep    tion
##[debug]    + FullyQualifiedErrorId : CommandNotFoundException,Import-DatabricksFolder
##[debug] 
##[debug]Script stack trace:
##[debug]at Import-DatabricksFolder, C:\Data\Agent\_work\_tasks\databricksDeployScripts_e7e6f2ae-fe5e-4191-9fd3-dbd811fa72e7\0.9.2916\ps_modules\azure.databricks.cicd.tools\Public\Import-DatabricksFolder.ps1: line 141
##[debug]at <ScriptBlock>, C:\Data\Agent\_work\_tasks\databricksDeployScripts_e7e6f2ae-fe5e-4191-9fd3-dbd811fa72e7\0.9.2916\vstsDeploy.ps1: line 53
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.CommandNotFoundException: The term 'Start-ThreadJob' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
```

ThreadJob installation logs
```
##[debug]00:00:00.2800304 Calling 'WebDownloader::DownloadFile' 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409','C:\windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft.PackageManagement\xi05pio4.vjq','40000','False'
##[debug]00:00:00.4017616 Attempting to load PowerShell Provider Module [C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1]
##[debug]00:00:00.6121007 Calling 'WebDownloader::DownloadFile' 'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag','C:\windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft.PackageManagement\bsobjgg3.unm','40000','False'
##[debug]00:00:00.7345901 Calling 'WebDownloader::DownloadFile' 'https://onegetcdn.azureedge.net/providers/psl-1.0.0.210.package.swidtag','C:\windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft.PackageManagement\retgeyav.4le','40000','False'
##[debug]00:00:00.7355338 Loaded PowerShell package provider: '[C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1]'.
##[debug]00:00:00.7395701 Loaded PowerShell Provider: PowerShellGet
##[debug]00:00:00.7408448 Initializing provider 'PowerShellGet'
##[debug]00:00:00.7455221 Calling New() : MethodName = 'InitializeProvider'
##[debug]00:00:00.7455596 ErrorAction: SilentlyContinue
##[debug]00:00:00.7455713 Name: ThreadJob
##[debug]00:00:00.7455805 MinimumVersion: 2.0.3
##[debug]00:00:00.7482565 INVOKING PowerShell Fn Initialize-Provider with args  that has length 0
##[debug]00:00:00.7656261 Calling 'WebDownloader::DownloadFile' 'https://onegetcdn.azureedge.net/providers/ChocolateyPrototype-2.8.5.130.package.swidtag','C:\windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft.PackageManagement\kwfrmwwh.eed','40000','False'
##[debug]00:00:00.8399628 In PowerShellGet Provider - 'Initialize-Provider'.
##[debug]00:00:00.8402067 PowerShell Script 'PSModule' Function 'Initialize-Provider' returns null.
##[debug]00:00:00.8410722 Done calling powershell «Initialize-Provider» «PSModule»
##[debug]00:00:00.8411301 Provider 'PowerShellGet' Initialized
##[debug]00:00:00.8411531 Using Package Provider PowerShellGet
##[debug]00:00:00.8478404 Calling New() : MethodName = 'GetFeatures'
##[debug]00:00:00.8478746 ErrorAction: SilentlyContinue
##[debug]00:00:00.8478892 Name: ThreadJob
##[debug]00:00:00.8479036 MinimumVersion: 2.0.3
##[debug]00:00:00.8489491 INVOKING PowerShell Fn Get-Feature with args  that has length 0
##[debug]00:00:00.9236434 In PowerShellGet Provider - 'Get-Feature'.
##[debug]00:00:00.9408039 Done calling powershell «Get-Feature» «PSModule»
##[debug]00:00:00.9409510 The provider 'PowerShellGet' is imported
##[debug]00:00:00.9420337 SUCCESS provider assembly: C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.4.7\fullclr\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
##[debug]00:00:00.9637534 Calling New() : MethodName = 'GetDynamicOptions'
##[debug]00:00:00.9637994 ErrorAction: SilentlyContinue
##[debug]00:00:00.9638172 Name: ThreadJob
##[debug]00:00:00.9638304 MinimumVersion: 2.0.3
```

Any pointers to what might be happening?

**Comment by simondmorias** [comment]
Which agent are you running on, self hosted or the built in hosted one? Basically this task depends on a module called ThreadJob being installed - which it should be on the hosted agent. On self hosted maybe you have a pool of machines with some having it installed and others not?

On a self hosted agent you could run Install-Module ThreadJob and in theory you will not see this again,

**Comment by elwinarens** [comment]
It's a custom agent idd. Good to hear that the hosted agent supports it. I'll see if i can have them install the module by default. Currently only CurrenUser scope is allowed and that doesn't always work.
